"""Tests for server/ut_tracker.py's pure output parser (no subprocess involved)."""

from __future__ import annotations

import pathlib

from server.ut_tracker import find_duplicate_player_name, parse_ut_output

# Captured verbatim from a real ArchipelagoLauncherDebug.exe "Universal
# Tracker" -- --nogui --list run (AP 0.6.7, 2026-09-21) against a room with
# apworld manifest warnings and a two-player Players/ folder.
REAL_STDOUT = (
    "Archipelago (0.6.7) logging initialized on Windows-11 process 27224\n"
    "Invalid or missing manifest file for C:\\...\\Hades2Rogue.apworld. This apworld will stop working with Archipelago 0.7.0.\n"
    "compatible_version - This might be the incorrect world version for this file\n"
    "P1 Weights: Dopamine.yaml >> Generated by https://archipelago.gg/ for Blasphemous\n"
    "P2 Weights: Portalisse.yaml >> My Hades2Rogue Template\n"
    "Generating for 2 players, 33101836229391285436 Seed 90600284999023336964 with plando: connections, texts, bosses\n"
    "Dopamine (Team #1) tracking Blasphemous has joined. Client(0.6.7), ['Tracker', 'AP'].\n"
    "Now that you are connected, you can use !help to list commands to run via the server.\n"
    "Beginning gift\n"
    "THL: Deogracias' gift\n"
    "Albero: Tirso's house, top floor\n"
)


def test_parse_ut_output_real_capture():
    assert parse_ut_output(REAL_STDOUT) == [
        "Beginning gift",
        "THL: Deogracias' gift",
        "Albero: Tirso's house, top floor",
    ]


# Captured verbatim from a real run (AP 0.6.7, 2026-09-23) where the location
# list printed BEFORE the connect handshake/join notice, the opposite order
# from REAL_STDOUT above. Confirms the parser doesn't anchor on line position.
REAL_STDOUT_LIST_BEFORE_HANDSHAKE = (
    "Invalid or missing manifest file for C:\\...\\Twilight Princess.apworld. This apworld will stop working with Archipelago 0.7.0.\n"
    "There is no item named 'archipelago.json' in the archive - This might be the incorrect world version for this file\n"
    "P1 Weights: Bran Zelda.yaml >> Generated by https://archipelago.gg/ for Twilight Princess\n"
    "Generating for 1 players, 12345 Seed 67890 with plando: connections, texts, bosses\n"
    "0 \n"
    "0 2 \n"
    "0 2 3 \n"
    "Barnes Bomb Bag\n"
    "Coro Bottle\n"
    "Herding Goats Reward\n"
    "Bran Zelda (Team #1) tracking Twilight Princess has joined. Client(0.6.7), ['AP', 'Tracker'].\n"
    "Now that you are connected, you can use !help to list commands to run via the server.\n"
)


def test_parse_ut_output_list_before_handshake():
    assert parse_ut_output(REAL_STDOUT_LIST_BEFORE_HANDSHAKE) == [
        "Barnes Bomb Bag",
        "Coro Bottle",
        "Herding Goats Reward",
    ]


def test_parse_ut_output_drops_generation_traceback():
    stdout = (
        "Generating for 3 players, 123 Seed 456 with plando: connections\n"
        "Traceback (most recent call last):\n"
        '  File "TrackerCore.py", line 331, in run_generator\n'
        "    g_args, seed = GMain(args)\n"
        "                   ^^^^^^^^^^^\n"
        "ValueError: Encountered 1 error(s) in player files.\n"
        "\n"
        "1. File Dopamine.yaml document #1 (name: Dopamine) is invalid. Please fix your yaml.\n"
        "Exception: No world found to handle game Blasphemous.\n"
        "Now that you are connected, you can use !help to list commands to run via the server.\n"
        "Real Location\n"
    )
    assert parse_ut_output(stdout) == ["Real Location"]


def test_parse_ut_output_drops_notices_after_the_list_starts():
    stdout = (
        "Now that you are connected, you can use !help to list commands to run via the server.\n"
        "Real Location\n"
        "Notice (all): someone else has stopped tracking the game.\n"
        "Another Location\n"
    )
    assert parse_ut_output(stdout) == ["Real Location", "Another Location"]


def test_parse_ut_output_empty_when_never_connects():
    stdout = "Archipelago (0.6.7) logging initialized\nConnection refused by the server.\n"
    assert parse_ut_output(stdout) == []


def test_parse_ut_output_handles_empty_string():
    assert parse_ut_output("") == []


def test_parse_ut_output_is_case_insensitive_for_filler_line():
    stdout = (
        "Now that you are connected, you can use !help to list commands to run via the server.\n"
        "ADDING 3 FILLER ITEMS TO THE POOL\n"
        "Real Location\n"
    )
    assert parse_ut_output(stdout) == ["Real Location"]


def test_find_duplicate_player_name_detects_collision(tmp_path: pathlib.Path):
    (tmp_path / "Portalis.yaml").write_text("name: Portalis\ngame: Hades2Rogue\n")
    (tmp_path / "Portalisse.yaml").write_text("name: Portalis\ngame: Hades2Rogue\n")
    assert find_duplicate_player_name(tmp_path) == "Portalis"


def test_find_duplicate_player_name_none_when_unique(tmp_path: pathlib.Path):
    (tmp_path / "Dopamine.yaml").write_text("name: Dopamine\ngame: Blasphemous\n")
    (tmp_path / "Portalis.yaml").write_text("name: Portalis\ngame: Hades2Rogue\n")
    assert find_duplicate_player_name(tmp_path) is None
